---
- name: Run the equivalent of "pacman -Syu"
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Install packages from manifest
  pacman:
    name: "{{ pacman['packages'] }}"
    state: latest
  become: yes
