---
- name: Copy chunkwmrc
  copy:
    src: chunkwmrc
    dest: ~/.chunkwmrc
    mode: 0755
  register: chunkwmrc_copy

- name: Restart chunkwm
  shell: |
    brew services restart crisidev/chunkwm/chunkwm
  when: chunkwmrc_copy.changed
