---
- name: Copy Brewfile
  copy:
    src: Brewfile
    dest: ~/.Brewfile
    mode: 0644

- name: Cleanup packages not found in manifest
  shell: |
    brew bundle cleanup --file=~/.Brewfile --force
  changed_when: "homebrew_cleanup.stdout_lines|length"
  register: homebrew_cleanup

- name: Print homebrew cleanup stdout
  debug:
    var: homebrew_cleanup.stdout_lines
    verbosity: 2

- name: Install packages from manifest
  shell: |
    brew bundle install --file=~/.Brewfile
  changed_when: "'Installed' in homebrew_install.stdout"
  register: homebrew_install

- name: Print homebrew packages install stdout
  debug:
    var: homebrew_install.stdout_lines
    verbosity: 2

- name: Update homebrew and upgrade all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Update homebrew cask and upgrade all packages
  homebrew_cask:
    upgrade_all: true
