---
- name: Download homebrew installer
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: /tmp

- name: Install homebrew
  command: /usr/bin/ruby -e /tmp/install
  register: install_homebrew

- name: Print homebrew install stdout
  debug:
    var: install_homebrew.stdout_lines
    verbosity: 2
