---
- name: Check for homebrew installation
  shell: |
    command -v brew &>/dev/null
  changed_when: False
  failed_when: False
  register: homebrew_check

- include_tasks: install-homebrew.yml
  when: homebrew_check is failed

- include_tasks: homebrew.yml
- include_tasks: chunkwm.yml
- include_tasks: skhd.yml
