---
- name: Check for homebrew installation
  command: command -v brew &>/dev/null
  register: homebrew_check

- include_tasks: install-homebrew.yml
  when: homebrew_check.rc != 0

- include_tasks: homebrew.yml
- include_tasks: chunkwm.yml
- include_tasks: skhd.yml
- include_tasks: ubersicht.yml
