---
- name: Copy skhdrc
  copy:
    src: skhdrc
    dest: "{{ skhdrc_dest }}"
    mode: 0644
  register: skhdrc_copy

- name: Restart skhd
  shell: |
    brew services restart koekeishiya/formulae/skhd
  when: skhdrc_copy.changed
