---
- name: Install pacman dependencies
  pacman:
    name: "{{ pacman['packages'] }}"
    update_cache: yes
    state: latest
  become: yes

- name: Enable and start cronie
  systemd:
    name: cronie
    enabled: yes
    state: started
  become: yes
