---
- name: Install homebrew dependencies
  homebrew:
    name: "{{ homebrew['brews'] }}"
    state: present
  notify: restart-logrotate

- name: Create launchd entry to clone/pull git repository
  template:
    src: library_launchagents_dotfiles.j2
    dest: "/Library/LaunchAgents/com.{{ ansible_user_id | regex_replace('\\.', '') }}.dotfiles.plist"
    owner: root
    group: wheel
    mode: 0644
  become: yes
