---
- name: Install homebrew dependencies
  homebrew:
    name: "{{ homebrew['brews'] }}"
    state: present

- name: Add ansible-pull launchd configuration to root LaunchAgents
  template:
    src: launchagents_dotfiles.j2
    dest: "/Library/LaunchAgents/com.{{ ansible_user_id | regex_replace('\\.', '') }}.dotfiles.plist"
  become: yes

- name: Run launchd configuration
  launchd:
    name: "com.{{ ansible_user_id | regex_replace('\\.', '') }}.dotfiles"
    state: started
  become: yes
