---
- name: Ensure util config file directories
  file:
    path: "{{ config.value|dirname }}"
    mode: 0700
    state: directory
  loop: "{{ util_config_files|dict2items }}"
  loop_control:
    loop_var: config

- name: Copy util config files
  copy:
    src: "{{ config.key }}"
    dest: "{{ config.value }}"
    mode: 0644
  loop: "{{ util_config_files|dict2items }}"
  loop_control:
    loop_var: config

- name: Ensure util config template directories
  file:
    path: "{{ config.value|dirname }}"
    mode: 0700
    state: directory
  loop: "{{ util_config_templates|dict2items }}"
  loop_control:
    loop_var: config

- name: Copy util config templates
  template:
    src: "{{ config.key }}"
    dest: "{{ config.value }}"
    mode: 0644
  loop: "{{ util_config_templates|dict2items }}"
  loop_control:
    loop_var: config

- name: Configure ssh dotfiles
  block:
    - name: Ensure ssh directory
      file:
        path: "{{ ansible_user_dir }}/.ssh"
        mode: 0700
        state: directory

    - name: Copy ssh config
      copy:
        content: "{{ ssh['config'] }}"
        dest: "{{ ansible_user_dir }}/.ssh/config"
        mode: 0644

    - name: Copy ssh public keys
      copy:
        content: "{{ keyfile.value }}"
        dest: "{{ ansible_user_dir }}/.ssh/{{ keyfile.key }}"
        mode: 0644
      loop: "{{ ssh['public_keys'] | dict2items }}"
      loop_control:
        loop_var: keyfile
      no_log: True

    - name: Copy ssh private keys
      copy:
        content: "{{ keyfile.value }}"
        dest: "{{ ansible_user_dir }}/.ssh/{{ keyfile.key }}"
        mode: 0600
      loop: "{{ ssh['private_keys'] |dict2items }}"
      loop_control:
        loop_var: keyfile
      no_log: True
  when: ssh is defined
