---
- name: Copy gpg-agent.conf
  template:
    src: gpg-agent.conf.j2
    dest: ~/.gnupg/gpg-agent.conf
    mode: 0644

- name: Copy htoprc
  copy:
    src: htoprc
    dest: ~/.config/htop/htoprc
    mode: 0644

- name: Copy ssh config
  copy:
    content: "{{ ssh_config }}"
    dest: ~/.ssh/config
    mode: 0644

- name: Copy ssh public keys
  copy:
    content: "{{ item.value }}"
    dest: "~/.ssh/{{ item.key }}"
    mode: 0644
  with_dict: "{{ ssh_public_keys }}"

- name: Copy ssh private keys
  copy:
    content: "{{ item.value }}"
    dest: "~/.ssh/{{ item.key }}"
    mode: 0600
  with_dict: "{{ ssh_private_keys }}"

- name: Copy tmux.conf
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf
    mode: 0644

- name: Copy zshrc
  copy:
    src: zshrc
    dest: ~/.zshrc
    mode: 0644
