---
- name: Ensure util config file directories
  file:
    path: "{{ config.value|dirname }}"
    mode: 0700
    state: directory
  loop: "{{ util_config_files|dict2items }}"
  loop_control:
    loop_var: config

- name: Copy util config files
  copy:
    src: "{{ config.key }}"
    dest: "{{ config.value }}"
    mode: 0644
  loop: "{{ util_config_files|dict2items }}"
  loop_control:
    loop_var: config

- name: Ensure util config template directories
  file:
    path: "{{ config.value|dirname }}"
    mode: 0700
    state: directory
  loop: "{{ util_config_templates|dict2items }}"
  loop_control:
    loop_var: config

- name: Copy util config templates
  template:
    src: "{{ config.key }}"
    dest: "{{ config.value }}"
    mode: 0644
  loop: "{{ util_config_templates|dict2items }}"
  loop_control:
    loop_var: config

- name: Ensure ssh directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory

- name: Copy ssh config
  copy:
    content: "{{ ssh_config }}"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    mode: 0644

- name: Copy ssh public keys
  copy:
    content: "{{ keyfile.value }}"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ keyfile.key }}"
    mode: 0644
  loop: "{{ ssh_public_keys|dict2items }}"
  loop_control:
    loop_var: keyfile
  no_log: True

- name: Copy ssh private keys
  copy:
    content: "{{ keyfile.value }}"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ keyfile.key }}"
    mode: 0600
  loop: "{{ ssh_private_keys|dict2items }}"
  loop_control:
    loop_var: keyfile
  no_log: True
