---
- include_tasks: zsh.yml

- name: Copy gpg-agent.conf
  template:
    src: gpg-agent.conf.j2
    dest: ~/.gnupg/gpg-agent.conf

- name: Ensure ~/.config/htop
  file:
    path: ~/.config/htop
    state: directory

- name: Copy htoprc
  copy:
    src: htoprc
    dest: ~/.config/htop/htoprc

- name: Synchronize fzf
  synchronize:
    src: fzf/
    dest: ~/.fzf/
    checksum: yes
    recursive: yes
    times: no
  register: fzf_sync

- include_tasks: install_fzf.yml
  when: fzf_sync.changed

- name: Copy tmux.conf
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: Ensure ~/.ssh
  file:
    path: ~/.ssh
    mode: 0700
    state: directory

- name: Copy id_rsa.pub
  copy:
    src: id_rsa.pub
    dest: ~/.ssh/id_rsa.pub

- name: Copy id_rsa
  copy:
    src: id_rsa
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: Copy algo.pem
  copy:
    src: algo.pem
    dest: ~/.ssh/algo.pem
    mode: 0600

- name: Copy ssh config
  copy:
    src: config
    dest: ~/.ssh/config
