---
- name: Synchronize base16-shell
  synchronize:
    src: base16-shell/
    dest: ~/.config/base16-shell
    checksum: yes
    recursive: yes
    times: no

- name: Synchronize fast-syntax-highlighting
  synchronize:
    src: fast-syntax-highlighting/
    dest: ~/.fsh
    checksum: yes
    recursive: yes
    times: no

- name: Synchronize fzf
  synchronize:
    src: fzf/
    dest: ~/.fzf/
    checksum: yes
    recursive: yes
    times: no
  register: fzf_sync

- include_tasks: install_fzf.yml
  when: fzf_sync.changed

- name: Synchronize geometry
  synchronize:
    src: geometry/
    dest: ~/.geometry
    checksum: yes
    recursive: yes
    times: no

- name: Synchronize oh-my-zsh
  synchronize:
    src: oh-my-zsh/
    dest: ~/.oh-my-zsh
    checksum: yes
    recursive: yes
    times: no
