---
- name: Copy gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ gitconfig_dest }}"
    mode: 0644

- name: Copy gitignore_global
  copy:
    src: gitignore_global
    dest: "{{ gitignore_global_dest }}"
    mode: 0644
