#!/bin/bash -e

FZF_DIR="$HOME/.fzf"

# Command-line fuzzy finder written in Go
if [ -d $FZF_DIR ]; then
  pushd $FZF_DIR > /dev/null
  git checkout master
  git pull
  ./install --all
  popd > /dev/null
fi
