- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.gitignore_global: gitignore_global
    ~/.oh-my-zsh: oh-my-zsh
    ~/.slimzsh: slimzsh
    ~/.tmux.conf: tmux.conf
    ~/.zshrc: zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
