- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.gitignore_global: default/gitignore_global
    ~/.oh-my-zsh: oh-my-zsh
    ~/.slimzsh: slimzsh
    ~/.tmux.conf: default/tmux.conf
    ~/.zshrc: default/zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
