- defaults:
    link:
      relink: true
      create: true

- clean: ['~']

- link:
    ~/.Brewfile: Brewfile
    ~/.config/nvim/init.vim: init.vim
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.oh-my-zsh: oh-my-zsh
    ~/.slimzsh: slimzsh
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [vim/install_dein, Installing dein]
