- defaults:
    link:
      relink: true
    shell:
      stdout: true
      stderr: true

- clean: ['~']

- link:
    ~/.fzf: utils/fzf
    ~/.tmux.conf: utils/tmux.conf

- shell:
  - [scripts/install_fzf, Installing fzf]
