- defaults:
    link:
      relink: true
      create: true

- clean: ['~']

- link:
    ~/.config/nvim/init.vim: vim/init.vim
    ~/.vimrc: vim/vimrc

- shell:
  - [scripts/install_dein, Installing dein]
