- defaults:
    link:
      relink: true
      create: true
    shell:
      stdout: true
      stderr: true

- clean: ['~']

- link:
    ~/.config/base16-shell: zsh/base16-shell
    ~/.oh-my-zsh: zsh/oh-my-zsh
    ~/.zfunctions/prompt_spaceship_setup: zsh/spaceship-prompt/spaceship.zsh
    ~/.zshrc: zsh/zshrc
