---
- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: build
  register: temp_dir

- name: Download dein installer
  get_url:
    url: "{{ dein['url'] }}"
    dest: "{{ temp_dir.path }}"

- name: Execute dein installer
  script: "{{ temp_dir.path }}/installer.sh {{ vim_bundles_directory }}"
  register: dein_installer

- name: Print dein installer stdout
  debug:
    var: dein_installer.stdout_lines
    verbosity: 2
