---
- name: Ensure vim config directories
  file:
    path: "{{ config.value|dirname }}"
    mode: 0700
    state: directory
  loop: "{{ vim_config_files|dict2items }}"
  loop_control:
    loop_var: config

- name: Copy vim config files
  copy:
    src: "{{ config.key }}"
    dest: "{{ config.value }}"
    mode: 0644
  loop: "{{ vim_config_files|dict2items }}"
  loop_control:
    loop_var: config

- name: Check vim base directory
  stat:
    path: "{{ vim_bundles_directory }}"
  register: dircheck

- include_tasks: install-dein.yml
  when: dircheck.stat.exists == False
