---
logfile: /var/log/dotfiles.log
repo_url: git://github.com/aglorei/dotfiles.git
schedule: '*/15 * * * *'
workdir: /tmp/dotfiles

homebrew:
  brews:
    - ansible
    - logrotate
pacman:
  packages:
    - ansible
    - cronie
